#ifndef _CUHOOK_H_
#define _CUHOOK_H_
#include <cuda.h>

typedef enum HookSymbolsEnum {
  CU_HOOK_MEM_ALLOC,
  CU_HOOK_MEM_ALLOC_MANAGED,
  CU_HOOK_MEM_ALLOC_PITCH,
  CU_HOOK_MEM_FREE,
  CU_HOOK_ARRAY_CREATE,
  CU_HOOK_ARRAY3D_CREATE,
  CU_HOOK_MIPMAPPED_ARRAY_CREATE,
  CU_HOOK_ARRAY_DESTROY,
  CU_HOOK_MIPMAPPED_ARRAY_DESTROY,
  CU_HOOK_CTX_GET_CURRENT,
  CU_HOOK_CTX_SET_CURRENT,
  CU_HOOK_CTX_DESTROY,
  CU_HOOK_LAUNCH_KERNEL,
  CU_HOOK_LAUNCH_COOPERATIVE_KERNEL,
  CU_HOOK_DEVICE_TOTOAL_MEM,
  CU_HOOK_MEM_INFO,
  CU_HOOK_CTX_SYNC,
  CU_HOOK_MEMCPY_ATOH,
  CU_HOOK_MEMCPY_DTOH,
  CU_HOOK_MEMCPY_HTOA,
  CU_HOOK_MEMCPY_HTOD,
  NUM_HOOK_SYMBOLS,
} HookSymbols;

#endif /* _CUHOOK_H_ */
